### ISSUE TITLE
[Bug] 社区作品观看量统计方式不合理

### ISSUE THREAD

**Issue by ghost** [Clipteam/clip-community#1]
**描述Bug**
Clip社区采用了统计作品绿旗被点击次数的方式来计算作品观看量, 但这是不合理的。这会导致一些问题，例如 [链接](https://codingclip.com/project/36) 。  
这个作品事实上实际观看人数并没有这么多, 但由于反复点击vm绿旗, 致使观看量甚至上升到了400+。如果未来别针社区不修复这个问题, 可能致使观看量统计数据完全没有参考价值。

**发生问题页面的链接**
https://codingclip.com/project/*

**复现步骤**
1. 打开任一作品  
2. 加载作品  
3. 记录当前的作品观看量  
4. 连续反复点击作品的绿旗  
5. 刷新页面  
6. 再次检查作品观看量, 进行比较

**预期的统计方式**
通过访问页面的IP数来进行统计, 单个IP访问多次仅算作一次。

**终端环境**
 - 设备: HUAWEI Mate 20 LYA-AL00
 - 操作系统: HarmonyOS 2.0.0.230
 - Webview: com.google.android.webview (102.0.5005.125/500512534)

**Comment by SimonShiki** [comment]
收到，已安排修复

**Comment by ghost** [comment]
好, 谢谢, 望尽快修复(?

**Comment by SimonShiki** [comment]
已修复
