### ISSUE TITLE
添加数组操作功能

### ISSUE THREAD

**Issue by bddjr** [Clipteam/clip-community#39]
很多时候，为了判断一个东西是否合规，通常要创建一个列表，非常的麻烦。

既然现在的数组已经支持项的解析和项的修改，建议支持以下积木块

< (["测试","123456"]) 包含 (测试) ? >

( 在数组 (["测试","123456"]) 的第 (0) 项前插入 (哦哦哦) )

**Comment by SimonShiki** [comment]
issue 与社区本体无关，请transfer到gui
