### ISSUE TITLE
reCAPTCHA框显示不清楚

### ISSUE THREAD

**Issue by Slouchwind** [Clipteam/clip-community#51]
如题  
看不清捏  
![image](https://user-images.githubusercontent.com/81954768/184086643-bee27682-0a6a-4345-8535-12a043de9cfa.png)

**Comment by pragma-Tism** [comment]
确实（

**Comment by pragma-Tism** [comment]
不过可能事浏览器的问题

**Comment by SimonShiki** [comment]
重复issue #52
